#!/bin/bash
#####  Constructed by HPC everywhere #####
#SBATCH --mail-user=yw132@iu.edu
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=48
#SBATCH --cpus-per-task=1
#SBATCH --time=0-12:0:00
#SBATCH --mail-type=FAIL,END
#SBATCH --job-name=my_job

######  Module commands #####
#module load deeplearning/2.3.0
##pip install ovito



######  Job commands go below this line #####
python by_layer_L2.py